import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import NavHeader from "@/components/shared/NavHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Montserrat font with desired weights
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can specify the weights you need
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can specify the weights you need
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${inter.variable} antialiased`}
      >
        <NavHeader />
        <Navbar montserrat={montserrat.className}/>
        {children}
      </body>
    </html>
  );
}
